require('plugins')
require('keymaps')
require('base')
require('colorscheme')

require('configs.lualine')
require('configs.lsp')
require('configs.code-completion')
require('configs.treesitter')
require('configs.telescope')
require('configs.pairing')
require('configs.null-ls')
require('configs.formatter-linter')
